# Generated by Django 6.0.3 on 2026-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='narxi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skidkasi',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tavsifi',
            field=models.TextField(null=True),
        ),
    ]
